export { default as AuthRepo } from './auth';
export { default as PickersRepo } from './pickers';
export { default as UsersRepo } from './users';
export { default as StaticPagesRepo } from './staticPages';
export { default as SideMenuRepo } from './sideMenu';
export { default as NotificationsRepo } from './notifications';
export { default as ContactUsRepo } from './contactUs';
export { default as AddressRepo } from './address';
export { default as ShipmentRepo } from './shipment';
